### ISSUE TITLE
Create a Gitter/Slack/etc channel

### ISSUE THREAD

**Issue by paulcarroty** [winepak/winepak#10]
Why:
* fast communication - don't need to find one from billion GH issues
* webhook notification - CI, build, software updates
* easy communication from outside people

**Comment by paulcarroty** [comment]
https://winepak.slack.com/

Please integrate the notifications: https://circleci.com/docs/2.0/notifications/#enable-chat-notifications

**Comment by julianrichen** [comment]
> Please integrate the notifications

I've added slack to the CircleCI project.

I think I mentioned before on another issue but I have little interest in using slack or a similar service. It requires you to login and can't be freely viewed by people, unlike the public repos. I have nothing against other members using it but I won't be participating, sorry.

**Comment by paulcarroty** [comment]
OK, please suggest the alternative for:

* the one and only CI aggregation
* chat with people, public/closed - it's possible on slack too
* automation tasks with third-party services like "your repo is gone" or "bad sync"
* sharing any private info like GPG keys and tokens

So, if you really think to handle all this stuff on github only - my condolences.
