### ISSUE TITLE
cannot follow installation guide on website

### ISSUE THREAD

**Issue by yasharne** [winepak/winepak#15]
Hi
I'm trying to install winepak via instruction on web page `https://www.winepak.org/`.
Everything works fine until step 4 which when I enter 
`flatpak install winepak tld.domain.Application` 
I get an error
 `error: Error searching remote winepak: Can't find ref tld.domain.Application`. 
I'm using ubuntu 18.04 amd64
How can I fix this?
Thanks

**Comment by paulcarroty** [comment]
@yasharne replace `tld.domain.Application` to `app.Which.You.Need.To.Install`.

**Comment by lazarvgd** [comment]
I have the same problem.

**Comment by julianrichen** [comment]
`tld.domain.Application` is an example of an application ID. flatpak uses reverse DNS app-ids to make application unique. You can see a list of what app-ids are by listing them:

```
$ flatpak remote-ls winepak
Ref                                     
com.blizzard.BattleNet.BaseApp          
com.blizzard.Overwatch                  
com.blizzard.StarCraft2                 
com.blizzard.WoW                        
com.leagueoflegends.Client              
com.oskarstalberg.Planet                
com.pathofexile.Client                  
com.worldoftanks.Client                 
info.cemu.Cemu                          
org.notepad_plus_plus.Notepad-plus-plus 
org.winepak.Platform                    
org.winepak.Platform.Compat32           
org.winepak.Platform.Extension.corefonts
org.winepak.Platform.Extension.d3dx9    
org.winepak.Platform.Extension.msls31   
org.winepak.Platform.Extension.vcrun2010
org.winepak.Platform.Extension.vcrun2012
org.winepak.Platform.Extension.vcrun2013
org.winepak.Platform.Extension.vcrun2015
org.winepak.Platform.Wine               
org.winepak.Platform.Wine.Compat32      
org.winepak.Sdk
```

or searching for them:
```
flatpak search league of legends
```

The app-ids that start with `org.winepak.*` will auto install with the app. You can install anything else (besides the Blizzard Base App).

So for League of Legends:
```
flatpak install winepak com.leagueoflegends.Client
```

**Comment by savbran** [comment]
flatpak install winepak com.blizzard.StarCraft2
Required runtime for com.blizzard.StarCraft2/x86_64/stable (runtime/org.winepak.Platform/x86_64/3.0) found in remote winepak
Do you want to install it? [y/n]: y
Installing: org.winepak.Platform/x86_64/3.0 from winepak
[####################] 15 delta parts, 125 loose fetched; 427951 KiB transferred in 621 seconds
error: Failed to install org.winepak.Platform/x86_64/3.0: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name :1.51 was not provided by any .service files
