### ISSUE TITLE
winepak.org cert is expired

### ISSUE THREAD

**Issue by TheCraiggers** [winepak/winepak#20]
I'm not sure if you are aware of this yet so I'm opening an issue.

winepak.org cert expired yesterday, and besides users having a hard time browsing the site, none of the flatpak commands will work normally as it uses TLS.

**Comment by jontis** [comment]
Confirmed. Site is blocked bacause the cert does not work.

**Comment by julianrichen** [comment]
Thank you both, apparently the automatic systemd service/timer I made didn't trigger like it should have. Certs have been renewed.
