### ISSUE TITLE
Problem with a installation of winepak 

### ISSUE THREAD

**Issue by MelkZ** [winepak/winepak#23]
I’m trying to install the app “winepak” and following this procedure in the terminal:
https://www.winepak.org/ 3
But always that I arrive in the last procedure (for to find the app in app center) pops up the following message:
Unable to load summary from remote winepak: GPG signatures found, but none are in trusted keyring.
How i Can to resolve it? I’m a basic user of Endless…

**Comment by anttirastas** [comment]
I guess this issue has to do with the issue I am having. I am trying to install StarCraft2 with Winepak, but the key seems to have expired on this week's Tuesday 9 June. See screenshot attached.

![image](https://user-images.githubusercontent.com/12835103/84563107-e85c0880-ad61-11ea-9bfc-347283273670.png)

**Comment by MelkZ** [comment]
I really don't' make ideia how to resolve it. I hope that someone have had this problem, but know how to resolve. Thank u for share your issue here.

**Comment by b3n** [comment]
cc @julianrichen

**Comment by vlad34** [comment]
Hi,

same problem.

**Comment by ernestofuk** [comment]
I have the same problem

**Comment by jjangga0214** [comment]
Same problem on Ubuntu 19.04.

```bash
$ flatpak remote-add --if-not-exists winepak https://dl.winepak.org/repo/winepak.flatpakrepo

error: Unable to load summary from remote winepak: GPG signatures found, but none are in trusted keyring
```

**Comment by julianrichen** [comment]
I swore I update the cert but maybe I did something wrong. I'll check when I have access to my main PC which can SSH into the box.

That said the project has admittedly been on pause as I work on other things. I'm not sure if anything is working atm as I haven't checked in months.

**Comment by julianrichen** [comment]
So I miss read the error and this is for the pgp not the SSL cert. I need to find the original private key used to build the files so I can update the pgp experiation to none. Since this would alter the key I'll likely need to rebuild everything, then generate a new public key so it's signed with that.

This is a bunch of work with little gain. The biggest issue with winepak, which is why I haven't been working on it, is that it all revolves around me building things instead of a remote server doing it and having people contribute. I really just need to get the buildbot & sdk in a place that it can auto build an push out. Then it can do all the signing and building again and this shouldn't happen. I just need to find the time.

For now you can include the repo without including the gpg signature:

```
flatpak remote-add --no-gpg-verify --if-not-exists winepak https://dl.winepak.org/repo/winepak.flatpakrepo
```

**Comment by MelkZ** [comment]
I tried to install without to include the gpg signature, but yet so, this won't worked.. the same message is being to show..

**Comment by MelkZ** [comment]
look:
[...]:~$ flatpak remote-add --no-gpg-verify --if-not-exists winepak https://dl.winepak.org/repo/winepak.flatpakrepo
[...]:~$ flatpak install winepak tld.domain.Application
Looking for matches…
error: Unable to load summary from remote winepak: GPG signatures found, but none are in trusted keyring



> I tried to install without to include the gpg signature, but yet so, this won't worked.. the same message is being to show..

**Comment by julianrichen** [comment]
Try?

```
flatpak remote-list
flatpak remote-delete winepak
flatpak remote-delete --user winepak
flatpak remote-add --no-gpg-verify --if-not-exists winepak https://dl.winepak.org/repo/winepak.flatpakrepo
flatpak install winepak tld.domain.Application
```

**Comment by MelkZ** [comment]
Now shows this: "error: Nothing matches tld.domain.Application in remote winepak"

**Comment by julianrichen** [comment]
`tld.domain.Application` isn't a real application, it's an example. You need to install an application like `com.leagueoflegends.Client`, `com.pathofexile.Client`, etc. You can list what is available with `flatpak remote-ls winepak`.

**Comment by MelkZ** [comment]
I tryed to install league of legends and appeared the following this message: "error: Failed to install org.winepak.Platform: Can't pull from untrusted non-gpg verified remote" waht's mean?
Edit: The same occurred for path of exile.

**Comment by MelkZ** [comment]
> I tryed to install league of legends and appeared the following this message: "error: Failed to install org.winepak.Platform: Can't pull from untrusted non-gpg verified remote" waht's mean?
> Edit: The same occurred for path of exile.

Sorry for many questions .. I really don't understand about this issues and I've difficulties cuz all is in english and I speak other language, to read things about computer systems is hard yet.

**Comment by MelkZ** [comment]
> I tryed to install league of legends and appeared the following this message: "error: Failed to install org.winepak.Platform: Can't pull from untrusted non-gpg verified remote" waht's mean?
> Edit: The same occurred for path of exile.

Update: I was able to install using "sudo" before the installation command

**Comment by RogueScholar** [comment]
@julianrichen Perhaps it's worth making this a sticky atop the Issues page until such time as it's properly resolved by the infrastructure buildout you describe above. It's a bit hidden here in the Closed section.

**Comment by MelkZ** [comment]
> @julianrichen Perhaps it's worth making this a sticky atop the Issues page until such time as it's properly resolved by the infrastructure buildout you describe above. It's a bit hidden here in the Closed section.

How can I do it? This is the first time that I am in one discussion in the GitHub..

**Comment by julianrichen** [comment]
@RogueScholar Good idea, will do.
